### ISSUE TITLE
Prepare presentation for Audit 1

### ISSUE THREAD

**Issue by aiushiusi** [TSP-24/TSP-24#11]
This task is transferred from the former jira.

- [x] Add slices in Google Drive
- [x] Have a mock presentation 1 hour before the tutorial

**Comment by aiushiusi** [comment]
Relevant documents and presentation slides for [Audit 1](https://drive.google.com/drive/folders/1uZ6mxYWh1-FPfLICDpSnwBVKVg6xPtjm?hl=en_GB).

**Comment by xuanan20020** [comment]
Completed as of 9th of March, 2024
