### ISSUE TITLE
Update existing documents - [Documentation]

### ISSUE THREAD

**Issue by aiushiusi** [TSP-24/TSP-24#12]
Due to the fee issue, we decided to drop Jira in favor of using Github to manage tasks and assignments. Hence, the landing page and some documents in Google Drive need some updates.

- [x] Update landing page (e.g: Jira link)
- [x] Update Agile guide
- [x] Update SoW

**Comment by xuanan20020** [comment]
As updated by Yifan:
- Agile Guide version 4.0 can be found [here](https://docs.google.com/document/d/1H_B2IR_oK5X_33vHWLSKQTa3lqXTOo9ebJ5G_A2v3t4/edit#heading=h.4ei8c2k4ohk0).

- SoW version 3.0 can be found [here](https://docs.google.com/document/d/1RIufymHDOEgsIpqSqa3FZnpXyiOQmKUT/edit).
