### ISSUE TITLE
Move tickets from Jira to GitHub [Management]

### ISSUE THREAD

**Issue by aiushiusi** [TSP-24/TSP-24#13]
Due to payment issues, we are transitioning from Jira to GitHub for task and assignment management. Our next steps include:
- [x] Convert Jira sprints into GitHub iterations.
- [x] Transfer the details from Jira tickets (including descriptions and acceptance criteria) into GitHub issues.

**Comment by aiushiusi** [comment]
<img width="794" alt="微信图片_20240424172347" src="https://github.com/TSP-24/TSP-24/assets/162016321/04cd62c8-21c6-48c6-b7ff-b3c6f045bc2e">

Received the reply of the Jira assistance Team.

**Comment by xuanan20020** [comment]
The conversion of Jira sprints to GitHub iterations is documented [here](https://docs.google.com/document/d/14zRGJtdcCSfJYiWiR-YMmDgvFwWC4s3mzgJbHGBg5Uc/edit#heading=h.4ei8c2k4ohk0).
