### ISSUE TITLE
Front-end coding refactoring [Front-end]

### ISSUE THREAD

**Issue by aiushiusi** [TSP-24/TSP-24#14]
Continue to update the code and fix some bugs.

**Comment by xuanan20020** [comment]
Lots of the scoring function code that remains in the **frontend** directory is rendered redundant after the scoring function is completed (see #10 ). The front-end team should look into deleting some of these codes :D.

**Comment by xuanan20020** [comment]
Finished refactoring by removing codes from both the back and front end [here](https://github.com/TSP-24/TSP-24/commit/8e3997193fa842e874b490228a0595aa5c4a9a39):
-  Remove venv variables and run on real environment in back end.
-  Remove redundant scoring function logic in front end.
