### ISSUE TITLE
Clean up Github branches

### ISSUE THREAD

**Issue by aiushiusi** [TSP-24/TSP-24#15]
We have some confusion with our github branch management, and there is a test repository which is empty. 
- [x] Merge backend branch into develop branch
- [x] Delete in-progress feature branches Kenney (no longer with the team) created

**Comment by xuanan20020** [comment]
Deleted and merged branches. More details are in item 20 of our [decision logs](https://docs.google.com/spreadsheets/d/1VQsDULPJ_I7BdywENEzqtF9Qaz7n0ISw/edit#gid=1485587477).
