### ISSUE TITLE
Update Risk/Decision-making/Reflection logs [Documentation]

### ISSUE THREAD

**Issue by aiushiusi** [TSP-24/TSP-24#17]
Since we lost our project manager, logs haven't been updated for 2 weeks.
Update logs in Google Drive, including not using Jira but using Github, use develop branch as back-end, client’s time constraint, our own time constraint.

**Comment by aiushiusi** [comment]
Updated recent decision-making and risk analysis.


Decision logs:
https://docs.google.com/spreadsheets/d/1VQsDULPJ_I7BdywENEzqtF9Qaz7n0ISw/edit#gid=1485587477

Risk logs:
https://docs.google.com/spreadsheets/d/18A-0CmFazu7Q95zG8i_yK_LBf9fjriUs/edit#gid=1859870860

**Comment by aiushiusi** [comment]
These document should be updates per sprint.

**Comment by xuanan20020** [comment]
Reflection Logs updated, see items 31-33:
https://docs.google.com/spreadsheets/d/1U86y1qBCeeqvwbpt5ffRyBbVjnG7XwsL/edit#gid=123066226
