### ISSUE TITLE
Preparation of the video

### ISSUE THREAD

**Issue by aiushiusi** [TSP-24/TSP-24#19]
Produce a 3 minute video that showcases your work

- Videos must be designed so that they can be available at the time of the showcase and assessed by tutors.
- Auxiliary materials are acceptable, however you must have an agreement with you tutor well in advance of the submission deadline, that they are happy to assess your linked online materials.

Because much of our engagement is online, with the consent of your tutor, you may produce an auxiliary linked online experience, using (for example) one of the following tools:

- https://shorthand.com/ (e.g. https://lnkd.in/fAUbGFj )
- Canva (e.g. https://www.canva.com/)
- WordPress (e.g. https://wordpress.com/)
- invision (https://www.invisionapp.com/) walkthrough
- vimeo/youtube (https://www.youtube.com/ or https://vimeo.com/)
- Google Site https://www.google.com/business/website-builder/

Also need to submit an 1-page A0 printable “Poster”, digital PDF file, associated with your video to Wattle. The PDF is not assessed.

- This will provide a link, and where relevant password, for your tutor and examiner to access and play your video.
- This will also include a 300 word description of your project, and a team biography.
- The Showcase this semester will be predominantly physical, with your PDF prominently displayed as a poster. Please bring a devise to share your video, and ensure you have a short url, or QR code, so that attendees can view your video on their device.

**Comment by xuanan20020** [comment]
The complete [video](https://drive.google.com/file/d/1aRG_kXJY_aWoejyLzwJVQARycUZLDop9/view) has been uploaded to our Google drive.
