### ISSUE TITLE
Technical and other constraints (eg. reliability, security, safety)

### ISSUE THREAD

**Issue by aiushiusi** [TSP-24/TSP-24#5]
This task is transferred from the former jira.
This task was to fulfill the document of Audit 1. The document was stored in Google Drive/Audit/Audit 1

**Comment by xuanan20020** [comment]
Finished as of Audit 1. Found in [costs and resources identification](https://docs.google.com/document/d/1NG7LAbTsErmQHZQPOpvYQOqoe7j4k8vq/edit) analysis, and [technical/other constraints identification](https://docs.google.com/document/d/1a5fgqek5dfYpzT05gy2nP5FmmOltHF8X/edit) analysis.
