### ISSUE TITLE
Problematisation analysis

### ISSUE THREAD

**Issue by aiushiusi** [TSP-24/TSP-24#6]
This task is transferred from the former jira.
This task was to fulfill the document of Audit 1. The document was stored in Google Drive/Audit/Audit 1
Aim to show evidence that the team complete a problematisation analysis supported by the Project Client Map.

**Comment by xuanan20020** [comment]
The [problematisation analysis](https://docs.google.com/document/d/1Dsh5Ffy6-n3WzVKYHViHBo4FbIu8YgwP2dnsHbbczvU/edit) was finished on 03/03/2024 in preparation for the SoW for Audit 1.
