### ISSUE TITLE
Prepare for the Audit 2 presentation

### ISSUE THREAD

**Issue by aiushiusi** [TSP-24/TSP-24#9]
This task is transferred from the former jira.

- [x] Add slices in Google Drive
- [x] Have a mock presentation 1 hour before the tutorial

**Comment by u7529136** [comment]
A demonstration video was made to show how our webpage works

**Comment by xuanan20020** [comment]
Relevant video demonstrations, illustrations, and presentation slides for [Audit 2](https://drive.google.com/drive/folders/1nzY55LWX_Wm2lMD8MFXf_NKoDvFV50s4?hl=en_GB).
